# Generated by Django 5.2 on 2025-06-12 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100, unique=True)),
                ('Tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Endereco', models.TextField()),
                ('Data_inicio', models.DateField()),
                ('Data_fim', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trabalhador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Funcao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EquipamentoRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantidade_usada', models.PositiveIntegerField(default=1)),
                ('Equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorios.equipamento')),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateField()),
                ('Clima', models.CharField(choices=[('sol', 'Ensolarado'), ('parcial', 'Parcialmente Nublado'), ('nublado', 'Nublado'), ('chuva', 'Chuvoso'), ('vento', 'Ventoso'), ('chuva_forte', 'Chuva Forte')], max_length=30)),
                ('Descricao', models.TextField(blank=True)),
                ('Equipamentos', models.ManyToManyField(blank=True, through='relatorios.EquipamentoRelatorio', to='relatorios.equipamento')),
                ('Obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='relatorios.obra')),
                ('Trabalhadores', models.ManyToManyField(blank=True, to='relatorios.trabalhador')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagem', models.ImageField(upload_to='relatorios/fotos/')),
                ('Relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='relatorios.relatorio')),
            ],
        ),
        migrations.AddField(
            model_name='equipamentorelatorio',
            name='Relatorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorios.relatorio'),
        ),
        migrations.AlterUniqueTogether(
            name='equipamentorelatorio',
            unique_together={('Relatorio', 'Equipamento')},
        ),
    ]
