# Generated by Django 5.2 on 2025-06-13 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='Obra',
            field=models.ForeignKey(blank=True, db_column='id_obra', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='relatorios.obra'),
        ),
    ]
