# Generated by Django 5.2 on 2025-06-13 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0003_alter_relatorio_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='Obra',
            field=models.ForeignKey(db_column='id_obra', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='relatorios.obra'),
        ),
    ]
