# Generated by Django 5.2 on 2025-08-02 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0004_alter_relatorio_obra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='Descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Obra', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='Obra',
            field=models.ForeignKey(db_column='id_obra', on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='relatorios.obra'),
        ),
    ]
