# Generated by Django 5.2 on 2025-08-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0006_alter_obra_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='Status',
            field=models.CharField(choices=[('andamento', 'Em andamento'), ('concluida', 'Concluída'), ('pausada', 'Em pausa'), ('cancelada', 'Cancelada')], default='andamento', max_length=20),
        ),
    ]
